version: '3.8'

services:
  # Backend (FastAPI)
  backend:
    container_name: plant-tracker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/plant_tracker
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - plant-tracker-network

  # Frontend (React)
  frontend:
    container_name: plant-tracker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - plant-tracker-network

  # Database (PostgreSQL)
  db:
    container_name: plant-tracker-db
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=plant_tracker
    ports:
      - "5432:5432"
    networks:
      - plant-tracker-network

networks:
  plant-tracker-network:
    driver: bridge

volumes:
  db-data:
